"""Generate the repository skills index from canonical plugin metadata."""

from __future__ import annotations

import argparse
from pathlib import Path

from skill_discovery import inventory


REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT = Path("docs/SKILLS_INDEX.md")
BANNER = "<!-- Generated by tools/build_skills_index.py; edit canonical plugin metadata instead. -->\n"


def render(repo_root: Path = REPO_ROOT) -> str:
    repo_root = repo_root.resolve()
    found = inventory(repo_root)
    lines = [BANNER, "# Security Playbook Skills\n", ""]
    for plugin in found.plugins:
        lines.extend((f"## {plugin.name}\n", "", f"{plugin.description}\n", ""))
        for skill in (item for item in found.skills if item.plugin == plugin):
            link = Path("..").joinpath(skill.path.relative_to(repo_root)).as_posix()
            lines.append(f"- [`{skill.name}`]({link}) — {skill.description}\n")
        lines.append("")
    unshipped = sorted((repo_root / ".claude/skills").glob("*/SKILL.md"))
    if unshipped:
        lines.extend(("## Claude-only entries\n", "", "These entries remain outside the two shipped plugins.\n", ""))
        for skill in unshipped:
            link = Path("..").joinpath(skill.relative_to(repo_root)).as_posix()
            lines.append(f"- [`{skill.parent.name}`]({link})\n")
    return "\n".join(lines).rstrip() + "\n"


def write_or_check(repo_root: Path = REPO_ROOT, *, check: bool = False) -> bool:
    repo_root = repo_root.resolve()
    target = repo_root / OUTPUT
    expected = render(repo_root)
    if check:
        return target.is_file() and target.read_text(encoding="utf-8") == expected
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(expected, encoding="utf-8")
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("command", choices=("build", "check"), nargs="?", default="build")
    parser.add_argument("--repo-root", type=Path, default=REPO_ROOT)
    args = parser.parse_args()
    if write_or_check(args.repo_root, check=args.command == "check"):
        return 0
    print(f"Generated file is stale: {args.repo_root / OUTPUT}")
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
